[workspace]
members = [ "8. Common collections/strings",
    # "1. Getting started/hello_cargo",
    # "2. Guessing game/guessing_game",
    # "3. Common programming concepts/branches",
    # "3. Common programming concepts/fahrenheit-celsius-converter",
    # "3. Common programming concepts/functions",
    # "3. Common programming concepts/invalid-array-index",
    # "3. Common programming concepts/loops",
    # "3. Common programming concepts/nth-fibonacci-number",
    # "3. Common programming concepts/rust-numbers",
    # "3. Common programming concepts/statements-expressions",
    # "3. Common programming concepts/variables",
    # "4. Understanding ownership/dangling_reference",
    # "4. Understanding ownership/ownership_functions",
    # "4. Understanding ownership/references_borrowing",
    # "4. Understanding ownership/return_values_scope",
    # "4. Understanding ownership/slices",
    # "4. Understanding ownership/string_slice_as_params",
    # "4. Understanding ownership/strings",
    # "5. Using structs/rectangles",
    # "5. Using structs/structs",
    # "5. Using structs/tuple-structs",
    # "6. Enums and pattern matching/enums",
    # "6. Enums and pattern matching/if-let-match",
    # "6. Enums and pattern matching/match-control-flow",
    # "7. Packages, crates and modules/restaurant",
    "8. Common collections/vectors",
    "8. Common collections/strings",
]
